'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { ChevronDown, ShieldCheck } from 'lucide-react';

interface HealthWaiverProps {
    accepted: boolean;
    onAcceptedChange: (accepted: boolean) => void;
    onAccept: () => void;
}

/** Within this many pixels of the bottom counts as having read to the end. */
const END_THRESHOLD_PX = 24;

/** Page background, matching `body` in globals.css; the pinned footer and its fade sit on it. */
const PAGE_BG = '#08080C';

const POINTS: { title: string; body: string }[] = [
    {
        title: 'Not medical advice.',
        body:
            'All content generated by SHaiPT, including workout plans, nutrition plans, and AI coach responses, is for general informational and fitness purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.',
    },
    {
        title: 'Consult your doctor.',
        body:
            'You should consult a qualified healthcare provider before starting any new exercise or nutrition program, especially if you have pre-existing medical conditions, injuries, or health concerns.',
    },
    {
        title: 'Exercise at your own risk.',
        body:
            'Physical exercise carries inherent risks of injury. You assume full responsibility for any injuries or health issues that may arise from following AI-generated fitness recommendations.',
    },
    {
        title: 'AI limitations.',
        body:
            'The AI coach and AI dietitian are not licensed professionals. Their guidance is based on general fitness and nutrition principles and may not account for your unique medical circumstances.',
    },
    {
        title: 'Form analysis disclaimer.',
        body:
            'The computer vision form checker is for guidance only. Always prioritize safe form and physical comfort over AI feedback.',
    },
];

/**
 * The health disclaimer, full-screen.
 *
 * The text flows in one scroll region that fills the screen — not a fixed-height box with its own
 * scrollbar, which on a phone hid most of the disclaimer and gave no hint that there was more.
 * The checkbox and the button are pinned to the bottom so the way forward is always in view, and a
 * "scroll to read the rest" cue sits above them until the reader has actually reached the end.
 * Nothing is gated on scrolling: the cue informs, it does not lock.
 */
export default function HealthWaiver({ accepted, onAcceptedChange, onAccept }: HealthWaiverProps) {
    const scrollRef = useRef<HTMLDivElement>(null);
    const [reachedEnd, setReachedEnd] = useState(false);

    const checkEnd = useCallback(() => {
        const el = scrollRef.current;
        if (!el) return;
        const remaining = el.scrollHeight - el.scrollTop - el.clientHeight;
        if (remaining <= END_THRESHOLD_PX) setReachedEnd(true);
    }, []);

    useEffect(() => {
        const el = scrollRef.current;
        if (!el) return;
        el.addEventListener('scroll', checkEnd, { passive: true });
        // ResizeObserver fires once right after observe(), which covers text that already fits
        // without scrolling, and again whenever the region changes size (rotation, keyboard).
        const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(checkEnd);
        observer?.observe(el);
        return () => {
            el.removeEventListener('scroll', checkEnd);
            observer?.disconnect();
        };
    }, [checkEnd]);

    const scrollToEnd = () => {
        const el = scrollRef.current;
        el?.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
    };

    return (
        <div className="flex flex-1 flex-col overflow-hidden" data-testid="health-waiver">
            {/* The disclaimer: one continuous read, scrolled by this region, no inner box. */}
            <div ref={scrollRef} className="flex-1 overflow-y-auto px-5 pb-10 pt-6 md:px-8">
                <div className="mx-auto w-full max-w-[600px]">
                    <div className="mb-5 flex items-center gap-3">
                        <div className="rounded-[10px] border border-brand/30 bg-[var(--brand-glow-soft)] p-2">
                            <ShieldCheck size={24} className="text-brand" />
                        </div>
                        <h1 className="font-display text-[1.15rem] font-bold leading-tight text-ink-hi">
                            Health Disclaimer &amp; Liability Waiver
                        </h1>
                    </div>

                    <p className="mb-5 text-[0.95rem] leading-[1.7] text-ink-mid">
                        SHaiPT uses artificial intelligence to generate personalized fitness training programs and
                        nutrition guidance. By proceeding, you acknowledge and agree to the following:
                    </p>

                    <ul className="list-disc space-y-4 pl-5">
                        {POINTS.map((point) => (
                            <li key={point.title}>
                                <p className="text-[0.95rem] leading-[1.7] text-ink-mid">
                                    <span className="font-bold text-ink-hi">{point.title}</span> {point.body}
                                </p>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            {/* Pinned footer: the way forward is always on screen. */}
            <div
                className="relative shrink-0 border-t border-[var(--line-soft)] px-5 pb-5 pt-4 md:px-8"
                style={{ background: PAGE_BG }}
            >
                {/* Fade over the last lines of text, so the cut-off itself reads as "there is more". */}
                <div
                    aria-hidden
                    className="pointer-events-none absolute inset-x-0 bottom-full h-16"
                    style={{ background: `linear-gradient(to top, ${PAGE_BG}, transparent)` }}
                />

                {!reachedEnd && (
                    <button
                        type="button"
                        onClick={scrollToEnd}
                        data-testid="waiver-scroll-cue"
                        className="absolute left-1/2 top-0 flex -translate-x-1/2 -translate-y-[calc(100%+12px)] items-center gap-1.5 rounded-full border border-[var(--line-soft)] bg-[var(--surface-2)] px-3.5 py-1.5 text-[0.78rem] font-semibold text-ink-hi shadow-lg backdrop-blur-md"
                    >
                        Scroll to read the rest
                        <ChevronDown size={14} className="animate-bounce" />
                    </button>
                )}

                <div className="mx-auto w-full max-w-[600px]">
                    <label
                        className={`mb-3 flex cursor-pointer items-start gap-3 rounded-[10px] border p-3 transition-all ${
                            accepted ? 'border-brand/30 bg-[var(--brand-glow-soft)]' : 'border-[var(--line-soft)] bg-transparent'
                        }`}
                    >
                        <input
                            type="checkbox"
                            checked={accepted}
                            onChange={(e) => onAcceptedChange(e.target.checked)}
                            className="mt-0.5 h-5 w-5 shrink-0 cursor-pointer accent-brand"
                        />
                        <p className="text-[0.85rem] leading-[1.55] text-ink-hi">
                            I understand that SHaiPT provides AI-generated fitness and nutrition advice, not medical
                            advice. I accept responsibility for my health decisions and will consult a healthcare
                            professional for medical concerns.
                        </p>
                    </label>

                    <button
                        onClick={onAccept}
                        disabled={!accepted}
                        data-testid="accept-waiver-btn"
                        className="btn-brand font-display w-full !py-3.5 !text-[0.9rem] disabled:cursor-not-allowed disabled:opacity-50"
                    >
                        Accept &amp; Continue to Interview
                    </button>
                </div>
            </div>
        </div>
    );
}
